# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	# OS
	config.vm.box = "opensuse/Leap-15.4.x86_64"

	# Default hardware setup
	config.vm.provider :libvirt do |libvirt|
		libvirt.cpus = 8
		# Normally specify this.  However, if specifying numa nodes
		# manually the sum of memory for each numa node will override
		# this.
		libvirt.memory = 16384
		# Specify numa nodes for the VM.
		libvirt.numa_nodes = [
			{:cpus => "0-3", :memory => "8192"},
			{:cpus => "4-7", :memory => "8192"}
		]
		# These do not have to be identical to eachother. EG:
		#libvirt.numa_nodes = [
		#	{:cpus => "0-3", :memory => "8192"},
		#	{:cpus => "4-5", :memory => "4096"},
		#	{:cpus => "6-7", :memory => "4096"}
		#]

		# Set clock to localtime instead of UTC
		libvirt.clock_offset = 'localtime'
	end

	# Pull over some useful files
	config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
	config.vm.provision "file", source: "~/.vimrc", destination: ".vimrc"
	#config.vm.provision "file", source: "~/.emacs", destination: ".emacs"

	# Enable x11 forwarding
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true

	# Disable NFS sync at start
	config.vm.synced_folder '.', '/vagrant', disabled: true

	# node definitions
	config.vm.define "leap15" do |slurm|
		slurm.vm.hostname = "leap15"
	end

	config.vm.provision "shell" do |shell|
		shell.reboot = true
		shell.inline =
			"zypper install -y -t pattern devel_basis
			zypper install -y check \
				dbus-1-devel \
				dejagnu \
				expect \
				freeipmi-devel \
				gdb \
				git \
				glib2-devel \
				gtk2-devel \
				hdf5-devel \
				http-parser-devel \
				hwloc \
				hwloc-devel \
				libcurl-devel \
				libevent-devel \
				libjson-c-devel \
				liblz4-devel \
				libmariadb-devel \
				libnuma-devel \
				libyaml-devel \
				lua53-devel \
				man \
				mariadb \
				mariadb-client \
				munge \
				munge-devel \
				ncurses-devel \
				numactl \
				pam-devel \
				perf \
				perl \
				perl-ExtUtils-MakeMaker \
				perl-ExtUtils-ParseXS \
				pmix-devel \
				python3 \
				rdma-core-devel \
				readline-devel \
				rpm-build \
				rrdtool-devel \
				tcpdump \
				valgrind \
				vim \
				which \
				xorg-x11-xauth
			echo thisismysecretmungekeythatis32bytes > /etc/munge/munge.key
			chown munge:munge /etc/munge/munge.key
			chmod 0400 /etc/munge/munge.key
			systemctl enable munge
			systemctl restart munge
			groupadd --gid 500 slurm
			useradd -r --uid 500 --gid 500 --shell /sbin/nologin slurm
			groupadd --gid 501 slurmrest
			useradd -r --uid 501 --gid 501 --shell /sbin/nologin slurmrest
			mkdir /var/log/slurm /var/spool/slurm /run/slurm
			chown slurm:slurm /var/log/slurm /var/spool/slurm /run/slurm
			echo -e \"d\t/run/slurm\t0755\tslurm\tslurm\t-\t-\" > /etc/tmpfiles.d/slurm.conf"
	end
end
