# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	# setup for all nodes
	config.vm.box = "generic/centos8"
	config.vm.synced_folder ".", "/vagrant", type: "nfs"
	config.vm.provider :libvirt do |libvirt|
		libvirt.cpus = 4
		libvirt.memory = 2048
	end

	config.vm.provision "shell", inline: <<-SHELL
		yum -y install dnf-plugins-core epel-release
		yum config-manager --set-enabled powertools
		yum -y install epel-release \
			expect \
			hdf5-devel \
			http-parser-devel \
			hwloc-devel \
			json-c-devel \
			libcurl-devel \
			libjwt-devel \
			libevent-devel \
			libibmad-devel \
			libibumad-devel \
			libssh2-devel \
			libyaml-devel \
			lua-devel \
			lz4-devel \
			man \
			man2html \
			mariadb \
			mariadb-devel \
			munge \
			munge-devel \
			ncurses-devel \
			numactl-devel \
			openssl-devel \
			pam-devel \
			perl-ExtUtils-MakeMaker \
			perl-ExtUtils-ParseXS \
			pmix-devel \
			python3 \
			readline-devel \
			rrdtool-devel \
			vim \
			which \
			git
		echo "thisismysecretmungekeythatis32bytes" > /etc/munge/munge.key
		chown munge:munge /etc/munge/munge.key
		chmod 0400 /etc/munge/munge.key
		systemctl disable httpd
		systemctl stop httpd
		systemctl enable munge
		systemctl restart munge
		echo -e "192.168.255.10\tdbd" >>/etc/hosts
		echo -e "192.168.255.11\tctld" >>/etc/hosts
		echo -e "192.168.255.12\tctld-backup" >>/etc/hosts
		groupadd --gid 500 slurm
		useradd --uid 500 --gid 500 --shell /sbin/nologin slurm
		mkdir /var/log/slurm /var/spool/slurm
		chown slurm:slurm /var/log/slurm /var/spool/slurm
	SHELL

	# node definitions
	config.vm.define "dbd" do |dbd|
		dbd.vm.hostname = "dbd"
		dbd.vm.network :private_network,
			:ip => '192.168.255.10',
			:libvirt__netmask => '255.255.255.0',
			:libvirt__network_name => 'clusternet',
			:libvirt__forward_mode => 'none'
		dbd.vm.provision "shell", inline: <<-SHELL
			yum -y install mariadb-server
			echo -e "[mysqld]\ninnodb_buffer_pool_size=1024M\ninnodb_log_file_size=64M\ninnodb_lock_wait_timeout=900" > /etc/my.cnf.d/slurm.cnf
			systemctl enable mariadb
			systemctl start mariadb
			mysql -e "create user slurm"
			mysql -e "create database slurm_acct_db"
			mysql -e "grant all on slurm_acct_db.* to 'slurm'"
		SHELL
	end
	config.vm.define "ctld" do |ctld|
		ctld.vm.hostname = "ctld"
		ctld.vm.network :private_network,
			:ip => '192.168.255.11',
			:libvirt__netmask => '255.255.255.0',
			:libvirt__network_name => 'clusternet',
			:libvirt__forward_mode => 'none'
	end
	config.vm.define "ctld-backup" do |ctldbak|
		ctldbak.vm.hostname = "ctld-backup"
		ctldbak.vm.network :private_network,
			:ip => '192.168.255.12',
			:libvirt__netmask => '255.255.255.0',
			:libvirt__network_name => 'clusternet',
			:libvirt__forward_mode => 'none'
	end

	nodecnt = ENV['NODES'] || 1
	(1..nodecnt).each do |i|
		config.vm.define "node#{i - 1}" do |node|
			node.vm.hostname = "node#{i - 1}"
			node.vm.network :private_network,
				:ip => "192.168.255.#{nodecnt + 99}",
				:libvirt__netmask => '255.255.255.0',
				:libvirt__network_name => 'clusternet',
				:libvirt__forward_mode => 'none'
			config.vm.provider :libvirt do |node|
				node.cpus = 4
				node.numa_nodes = [
					{:cpus => "0-1", :memory => "2048"},
					{:cpus => "2-3", :memory => "2048"},
				]
			end
		end
	end
end
